language: node_js
node_js:
- stable
cache:
- yarn
install:
- yarn install
script:
- yarn build
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: dist
  default_text_charset: utf-8
notifications:
  slack:
    secure: CniwoGaLDdLAnILQ2UHule4gmoHTywOYtBStvcrGk4V9nw21D+4yjOHSlLNNG0R76aphawxeH0OJX0a0a2ybN8sPX00KLRw+6rRcDlUM6m97j8STw2pcmG/4lIvmb10BR/OW1TRk51T3Tm3E0nMb3BuJVOlpy8yb/F8XOYRHJPP3L5nE4NAhCk2aYMEwSdWDcfD0JQXWgxjmvMNXY4flQ+r6g3iyEt5P62miBqdmlXCuLtk5V2ouzhVQsEM2IACPswuYWE2A+VLRnD9oe5HwKQDJq27RM3Lv5RD06UNwEjFcJ/7upcdbE0wbfs6HIIc5blk+UQ1p9+X55qnpj4td9nIFMIKj6Fn8+J7Y6IKPiQsq6dIzdjygj3DmvNgSgwk9squd+qDmHyiP87710NKG+CXmsnhlPwNWLgmBxPIhVsMf9IGFc5IrrqRBecTIn+8mlVuw5h8q4hIDBO81BF+FU6I3uNkzHmWfO/6ECHvrxkyZBchtTZSjPEMiGmdpq9cwA9VNj1QiN6XSJ/rFw+OKtRIgdbzIudv8MQTsUz/KxQP927ioj17LH3vUn2oVdQLwhcafXaLqbxGFL1/wSl4PCDJtGgW68Vbdc38/60MBbrx3ZUItR4wD8V7p58xZll1ZoAJpSJdh6Qs8LZhdyaHJt/4BXWLQNrckG0MeXSEWUxc=
